### ISSUE TITLE
medco-unlynx stops working after a long runtime

### ISSUE THREAD

**Issue by mickmis** [ldsec/medco#35]
It seems like after a long runtime (> 1 week), unlynx / medco-unlynx stop working and hangs. There is a chance that it might relate to the fact that some communications fail, and that errors out everything after.

Logs do not say much (this is a small extract, check out the logs on the AWS machines in `~/unlynx-long-runtime-bug_medco-connector_srvX.log` and `~/unlynx-long-runtime-bug_medco-unlynx_srvX.log` of each machine):

**medco-connector server 0**
```
medco-connector_1     | INFO[1513530] Token validation successful with provider: https://ec2-35-183-0-13.ca-central-1.compute.amazonaws.com/auth/realms/master/protocol/openid-connect/certs 
medco-connector_1     | INFO[1513530] authenticated user test                      
medco-connector_1     | INFO[1513530] user is authorized to request the endpoint with authorization medco-explore 
medco-connector_1     | INFO[1513530] user is authorized to execute the query type count_global_obfuscated 
medco-connector_1     | 2 : api.go:41 (services.(*API).SendSurveyDDTRequestTerms) - Client 0 is creating a DDT survey with ID: MedCo_Explore_Query_202026101158178_DDT
medco-connector_1     | ERRO[1513680] unlynx timeout                     
```

**medco-unlynx server 0**
```
medco-unlynx_1        | 1 : deterministic_tagging_protocol.go:139 (protocols.(*DeterministicTaggingProtocol).Start) - [tls://ec2-54-227-122-59.compute-1.amazonaws.com:2000]  starts a Deterministic Tagging Protocol on  1  element(s)
medco-unlynx_1        | 1 : deterministic_tagging_protocol.go:253 (protocols.(*DeterministicTaggingProtocol).Dispatch) - tls://ec2-54-227-122-59.compute-1.amazonaws.com:2000  carried on deterministic Tagging. 1
medco-unlynx_1        | 1 : deterministic_tagging_protocol.go:195 (protocols.(*DeterministicTaggingProtocol).Dispatch) - tls://ec2-54-227-122-59.compute-1.amazonaws.com:2000  preparation round for deterministic tagging
medco-unlynx_1        | 1 : deterministic_tagging_protocol.go:139 (protocols.(*DeterministicTaggingProtocol).Start) - [tls://ec2-54-227-122-59.compute-1.amazonaws.com:2000]  starts a Deterministic Tagging Protocol on  1  element(s)
medco-unlynx_1        | 1 : deterministic_tagging_protocol.go:139 (protocols.(*DeterministicTaggingProtocol).Start) - [tls://ec2-54-227-122-59.compute-1.amazonaws.com:2000]  starts a Deterministic Tagging Protocol on  1  element(s)
medco-unlynx_1        | E : overlay.go:604 (v3.(*Overlay).nodeDelete) - Error while closing node: Can't shutdown empty ProtocolInstance:
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*TreeNodeInstance).closeDispatch
medco-unlynx_1        |         /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/treenode.go:373
medco-unlynx_1        | E : overlay.go:116 (v3.(*Overlay).Process)   - Msg PTID(protocolsunlynx.DataReferenceMessage:9bd55e854c6e54ec894a7be9235d6eb7) from tls://ec2-35-183-0-13.ca-central-1.compute.amazonaws.com:2000 produced error: creating protocol:        |     go.dedis.ch/onet/v3.(*Overlay).TransmitMsg
medco-unlynx_1        |         /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/overlay.go:172
medco-unlynx_1        |   - creating protocol:
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*serviceManager).newProtocol
medco-unlynx_1        |         /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/service.go:547
medco-unlynx_1        |   - didn't get data within time - aborting:
medco-unlynx_1        |     github.com/ldsec/medco-unlynx/services.(*Service).NewProtocol
medco-unlynx_1        |         /src/services/service.go:618
medco-unlynx_1        | 1 : deterministic_tagging_protocol.go:251 (protocols.(*DeterministicTaggingProtocol).Dispatch) - tls://ec2-54-227-122-59.compute-1.amazonaws.com:2000  completed deterministic Tagging ( 1 row )
medco-unlynx_1        | E : service.go:121 (services.(*Service).HandleSurveyDDTRequestTerms) - couldn't finish tagging protocol in time
medco-unlynx_1        | E : websocket.go:296 (v3.wsHandler.ServeHTTP) - Got an error while executing medco/SurveyDDTRequest: processing error:
medco-unlynx_1        |     go.dedis.ch/onet/v3.callInterfaceFunc
medco-unlynx_1        |         /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/processor.go:440
medco-unlynx_1        |   - couldn't finish tagging protocol in time
medco-unlynx_1        | E : service.go:121 (services.(*Service).HandleSurveyDDTRequestTerms) - couldn't finish tagging protocol in time
medco-unlynx_1        | E : websocket.go:296 (v3.wsHandler.ServeHTTP) - Got an error while executing medco/SurveyDDTRequest: processing error:
medco-unlynx_1        |     go.dedis.ch/onet/v3.callInterfaceFunc
medco-unlynx_1        |         /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/processor.go:440
medco-unlynx_1        |   - couldn't finish tagging protocol in time
medco-unlynx_1        | E : overlay.go:604 (v3.(*Overlay).nodeDelete) - Error while closing node: Can't shutdown empty ProtocolInstance:
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*TreeNodeInstance).closeDispatch
medco-unlynx_1        |         /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/treenode.go:373
medco-unlynx_1        | E : overlay.go:116 (v3.(*Overlay).Process)   - Msg PTID(protocolsunlynx.DataReferenceMessage:9bd55e854c6e54ec894a7be9235d6eb7) from tls://ec2-54-93-247-56.eu-central-1.compute.amazonaws.com:2000 produced error: creating protocol:       |     go.dedis.ch/onet/v3.(*Overlay).TransmitMsg
medco-unlynx_1        |         /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/overlay.go:172
medco-unlynx_1        |   - creating protocol:
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*serviceManager).newProtocol
medco-unlynx_1        |         /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/service.go:547
medco-unlynx_1        |   - didn't get data within time - aborting:
medco-unlynx_1        |     github.com/ldsec/medco-unlynx/services.(*Service).NewProtocol
medco-unlynx_1        |         /src/services/service.go:618
medco-unlynx_1        | E : overlay.go:604 (v3.(*Overlay).nodeDelete) - Error while closing node: Can't shutdown empty ProtocolInstance:
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*TreeNodeInstance).closeDispatch
medco-unlynx_1        |         /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/treenode.go:373
medco-unlynx_1        | E : overlay.go:116 (v3.(*Overlay).Process)   - Msg PTID(protocolsunlynx.DeterministicTaggingBytesMessage:17fc28ca022c5869bb4c07d0deb697fa) from tls://ec2-35-183-0-13.ca-central-1.compute.amazonaws.com:2000 produced error: creating protocol:  go.dedis.ch/onet/v3.(*Overlay).TransmitMsg
medco-unlynx_1        |         /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/overlay.go:172
medco-unlynx_1        |   - could not create new protocol: tree should never be nil when called during a protocol; it might be that Tree() has been called after Done() which is wrong or the tree has not correctly been passed. at goroutine 836 [running]:       |     runtime/debug.Stack(0xc0001152d0, 0x9b8fc0, 0xb6f760)
medco-unlynx_1        |          /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
medco-unlynx_1        |     go.dedis.ch/onet/v3/log.Stack(...)
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/log/testutil.go:105
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*serviceManager).newProtocol.func2(0xc000115aa0, 0xc000115ab0)
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/service.go:538 +0x72
medco-unlynx_1        |     panic(0x9b8fc0, 0xb6f760)
medco-unlynx_1        |          /usr/local/go/src/runtime/panic.go:679 +0x1b2
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*TreeNodeInstance).Tree(...)
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/treenode.go:184
medco-unlynx_1        |     github.com/ldsec/unlynx/protocols.NewDeterministicTaggingProtocol(0xc000292120, 0x102, 0x102, 0x7fbe3049c428, 0xc0000575f0)
medco-unlynx_1        |          /go/pkg/mod/github.com/ldsec/unlynx@v1.4.0/protocols/deterministic_tagging_protocol.go:112 +0x408
medco-unlynx_1        |     github.com/ldsec/medco-unlynx/services.(*Service).NewProtocol(0xc0001ce640, 0xc000292120, 0xc00016b8f0, 0xb885e0, 0xc0001ce640, 0x1, 0xc0001159f0)
medco-unlynx_1        |          /src/services/service.go:517 +0x1348
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*serviceManager).newProtocol(0xc0002140f0, 0xc000292120, 0xc00016b8f0, 0x0, 0x0, 0x0, 0x0)
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/service.go:542 +0x19b
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*Overlay).TransmitMsg(0xc000182100, 0xc0002c3860, 0xb8ada0, 0xc000176090, 0x0, 0x0)
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/overlay.go:167 +0x445
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*Overlay).Process(0xc000182100, 0xc00006db00)
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/network/dispatch.go:95 +0x9f
medco-unlynx_1        |     go.dedis.ch/onet/v3/network.(*Router).handleConn(0xc0000969a0, 0xc0000cc500, 0xb8fdc0, 0xc000261260)
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/network/router.go:365 +0x2d4
medco-unlynx_1        |     created by go.dedis.ch/onet/v3/network.(*Router).launchHandleRoutine
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/network/router.go:410 +0x191:
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*serviceManager).newProtocol.func2
medco-unlynx_1        |         /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/service.go:537
medco-unlynx_1        | 1 : deterministic_tagging_protocol.go:195 (protocols.(*DeterministicTaggingProtocol).Dispatch) - tls://ec2-54-227-122-59.compute-1.amazonaws.com:2000  preparation round for deterministic tagging
medco-unlynx_1        | E : overlay.go:604 (v3.(*Overlay).nodeDelete) - Error while closing node: Can't shutdown empty ProtocolInstance:
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*TreeNodeInstance).closeDispatch
medco-unlynx_1        |         /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/treenode.go:373
medco-unlynx_1        | E : overlay.go:116 (v3.(*Overlay).Process)   - Msg PTID(protocolsunlynx.DeterministicTaggingBytesMessage:17fc28ca022c5869bb4c07d0deb697fa) from tls://ec2-35-183-0-13.ca-central-1.compute.amazonaws.com:2000 produced error: creating protocol:
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*Overlay).TransmitMsg
medco-unlynx_1        |         /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/overlay.go:172
medco-unlynx_1        |   - could not create new protocol: tree should never be nil when called during a protocol; it might be that Tree() has been called after Done() which is wrong or the tree has not correctly been passed. at goroutine 825 [running]:
medco-unlynx_1        |     runtime/debug.Stack(0xc0001172d0, 0x9b8fc0, 0xb6f760)
medco-unlynx_1        |          /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
medco-unlynx_1        |     go.dedis.ch/onet/v3/log.Stack(...)
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/log/testutil.go:105
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*serviceManager).newProtocol.func2(0xc000117aa0, 0xc000117ab0)
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/service.go:538 +0x72
medco-unlynx_1        |     panic(0x9b8fc0, 0xb6f760)
medco-unlynx_1        |          /usr/local/go/src/runtime/panic.go:679 +0x1b2
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*TreeNodeInstance).Tree(...)
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/treenode.go:184
medco-unlynx_1        |     github.com/ldsec/unlynx/protocols.NewDeterministicTaggingProtocol(0xc000292d80, 0x103, 0x103, 0x7fbe3049c428, 0xc0000575f0)
medco-unlynx_1        |          /go/pkg/mod/github.com/ldsec/unlynx@v1.4.0/protocols/deterministic_tagging_protocol.go:112 +0x408
medco-unlynx_1        |     github.com/ldsec/medco-unlynx/services.(*Service).NewProtocol(0xc0001ce640, 0xc000292d80, 0xc0002e0a50, 0xb885e0, 0xc0001ce640, 0x1, 0xc0001179f0)
medco-unlynx_1        |          /src/services/service.go:517 +0x1348
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*serviceManager).newProtocol(0xc0002140f0, 0xc000292d80, 0xc0002e0a50, 0x0, 0x0, 0x0, 0x0)
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/service.go:542 +0x19b
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*Overlay).TransmitMsg(0xc000182100, 0xc000168360, 0xb8ada0, 0xc000176090, 0x0, 0x0)
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/overlay.go:167 +0x445
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*Overlay).Process(0xc000182100, 0xc00006db80)
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/overlay.go:114 +0x337
medco-unlynx_1        |     go.dedis.ch/onet/v3/network.(*BlockingDispatcher).Dispatch(0xc00015d750, 0xc00006db80, 0x0, 0x0)
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/network/dispatch.go:95 +0x9f
medco-unlynx_1        |     go.dedis.ch/onet/v3/network.(*Router).handleConn(0xc0000969a0, 0xc0000cca00, 0xb8fdc0, 0xc0002612c0)
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/network/router.go:365 +0x2d4
medco-unlynx_1        |     created by go.dedis.ch/onet/v3/network.(*Router).launchHandleRoutine
medco-unlynx_1        |          /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/network/router.go:410 +0x191:
medco-unlynx_1        |     go.dedis.ch/onet/v3.(*serviceManager).newProtocol.func2
medco-unlynx_1        |         /go/pkg/mod/go.dedis.ch/onet/v3@v3.1.0/service.go:537
medco-unlynx_1        | 1 : deterministic_tagging_protocol.go:195 (protocols.(*DeterministicTaggingProtocol).Dispatch) - tls://ec2-54-227-122-59.compute-1.amazonaws.com:2000  preparation round for deterministic tagging
medco-unlynx_1        | 1 : deterministic_tagging_protocol.go:195 (protocols.(*DeterministicTaggingProtocol).Dispatch) - tls://ec2-54-227-122-59.compute-1.amazonaws.com:2000  preparation round for deterministic tagging
medco-unlynx_1        | 1 : deterministic_tagging_protocol.go:195 (protocols.(*DeterministicTaggingProtocol).Dispatch) - tls://ec2-54-227-122-59.compute-1.amazonaws.com:2000  preparation round for deterministic tagging
medco-unlynx_1        | 1 : deterministic_tagging_protocol.go:253 (protocols.(*DeterministicTaggingProtocol).Dispatch) - tls://ec2-54-227-122-59.compute-1.amazonaws.com:2000  carried on deterministic Tagging. 1
medco-unlynx_1        | 1 : deterministic_tagging_protocol.go:253 (protocols.(*DeterministicTaggingProtocol).Dispatch) - tls://ec2-54-227-122-59.compute-1.amazonaws.com:2000  carried on deterministic Tagging. 1
medco-unlynx_1        | 1 : deterministic_tagging_protocol.go:251 (protocols.(*DeterministicTaggingProtocol).Dispatch) - tls://ec2-54-227-122-59.compute-1.amazonaws.com:2000  completed deterministic Tagging ( 1 row )
medco-unlynx_1        | 1 : deterministic_tagging_protocol.go:251 (protocols.(*DeterministicTaggingProtocol).Dispatch) - tls://ec2-54-227-122-59.compute-1.amazonaws.com:2000  completed deterministic Tagging ( 1 row )
```

**Comment by JoaoAndreSa** [comment]
In three days is the one-year old anniversary of this issue and we've not had this problem for ages. @mickmis we can close this, no?

**Comment by mickmis** [comment]
> In three days is the one-year old anniversary of this issue and we've not had this problem for ages. @mickmis we can close this, no?

Come on let it have its birthday
